### ISSUE TITLE
Unfinished link to "Edit this page in Github"

### ISSUE THREAD

**Issue by kvutien** [ConsenSys-Academy/basic-training#29]
In [https://github.com/ConsenSys-Academy/basic-training/blob/main/M5/L6/index.html](https://github.com/ConsenSys-Academy/basic-training/blob/main/M5/L6/index.html) you forgot to edit the last link. There are still `MODULE_NUM` and `LESSON_NUM`

```html
https://github.com/ConsenSys-Academy/basic-training/edit/main/MODULE_NUM/LESSON_NUM/index.html
```
Also the link to [https://github.com/ConsenSys-Academy/pull-request-tutorial](https://github.com/ConsenSys-Academy/pull-request-tutorial) is an empty Github page.

**Comment by ConsenSys-Academy** [comment]
@kvutien Can you open a pull request for the module? Also happy to fix it but kind of more fun if you do!

And we're aware of the empty repo, still working on that!

**Comment by kvutien** [comment]
[Done](https://github.com/ConsenSys-Academy/basic-training/pull/34)

**Comment by ConsenSys-Academy** [comment]
Merged PR, thank you @kvutien !
