### ISSUE TITLE
Sentence to edit in Javascript vs Python

### ISSUE THREAD

**Issue by kvutien** [ConsenSys-Academy/basic-training#30]
In [page "Javascript vs Python"](https://github.com/ConsenSys-Academy/basic-training/edit/main/M6/L2/index.html)
this sentence would need to be edited to be understandable:

_An analogy might be a browser extension's relationship to a browser: the extension **needs to be installed by was developed by a third-party** to extend the capacity of the browser_

**Comment by ConsenSys-Academy** [comment]
@kvutien Not sure I totally understand, where would you like to add this? How would you like it to be edited? What's the general point you're hoping to convey?

**Comment by kvutien** [comment]
It's normal that you don't understand the sentence because I didn't understand either :)

In this page: [https://github.com/ConsenSys-Academy/basic-training/edit/main/M6/L2/index.html](https://github.com/ConsenSys-Academy/basic-training/edit/main/M6/L2/index.html)
you can read the sentence aloud. For me it is missing something to make sense: "installed by..." by what?

_An analogy might be a browser extension's relationship to a browser: the extension **needs to be installed by was developed by a third-party** to extend the capacity of the browser_

Am I mistaking?

**Comment by ConsenSys-Academy** [comment]
Ah! Okay, I wasn't sure where the line was you mentioned. Thanks for making that clear, I'll go clear it up now
