### ISSUE TITLE
typo in url on basic-training/M1/L1/index.htm

### ISSUE THREAD

**Issue by pclaesen** [ConsenSys-Academy/basic-training#4]
Line 48 of this file has a typo, states bsaic-training instead of basic-training.

**Comment by cooganb** [comment]
Thank you so much for finding this, @pclaesen! We haven't announced it but we're trying a more open model for our materials to encourage activity just like yours. Super cool. 

Are you interested in submitting a Pull Request with this change? We know it's minor, but just to try it out?

**Comment by pclaesen** [comment]
Yeah sure, will get it done today :D.

**Comment by ConsenSys-Academy** [comment]
@pclaesen thanks so much for this! we're going to be making this public via our learning management system next Tuesday, June 1st, would love your feedback on it if you're interested!

**Comment by pclaesen** [comment]
Yeah sure :).
